name: "process_singlesample_base"
namespace: "workflows/multiomics"
scope: "private"
description: "A pipeline to analyse a single multiomics sample."
authors:
  - __merge__: /src/authors/dorien_roosen.yaml
    roles: [ author ]

argument_groups:
  - name: Output State
    arguments:
      - name: --output_modality
        type: string
        direction: output
__merge__: [., /src/workflows/multiomics/process_singlesample/process_singlesample.yaml]

dependencies:
  - name: metadata/add_id
  - name: workflows/multiomics/split_modalities
    alias: split_modalities_workflow
  - name: workflows/rna/rna_singlesample
  - name: workflows/prot/prot_singlesample
  - name: workflows/gdo/gdo_singlesample

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - type: file
    path: /src/workflows/utils/

runners:
  - type: nextflow
