flowchart LR
   COUNT_TABLE((COUNT_TABLE))

   H5AD(H5AD)
   H5_CELLRANGER(H5_CELLRANGER)
   MTX(MTX)
   SEURAT(SEURAT)
   SCE(SCE)
   DGE(DGE)

   TO_H5AD

   H5AD_SPLIT

   H5AD_TX(H5AD_TX)
   H5AD_ADT(H5AD_ADT)
   H5AD_CUSTOM(H5AD_CUSTOM)
   H5AD_CRISPR(H5AD_CRISPR)


   COUNT_TABLE --> H5AD
   COUNT_TABLE --> H5_CELLRANGER
   COUNT_TABLE --> MTX
   COUNT_TABLE --> SEURAT
   COUNT_TABLE --> SCE
   COUNT_TABLE --> DGE

   H5_CELLRANGER --> TO_H5AD
   MTX --> TO_H5AD
   SEURAT --> TO_H5AD
   SCE --> TO_H5AD
   DGE --> TO_H5AD

   H5AD --> H5AD_SPLIT
   TO_H5AD --> H5AD_SPLIT
   
   H5AD_SPLIT --> H5AD_TX
   H5AD_SPLIT --> H5AD_ADT
   H5AD_SPLIT --> H5AD_CUSTOM
   H5AD_SPLIT --> H5AD_CRISPR




