stateDiagram-v2
    [*] --> BCL
    [*] --> FASTQ
    [*] --> COUNT_TABLE

    BCL --> PROCESSING
    FASTQ --> PROCESSING
    COUNT_TABLE --> PROCESSING

    PROCESSING --> H5AD_TX
    PROCESSING --> H5AD_ADT
    PROCESSING --> H5AD_ATAC


    H5AD_TX --> [*]
