flowchart LR
    SEQUENCER(SEQUENCER)
    DEMULTIPLEX[DEMULTIPLEX]
    COUNT[MAP/COUNT]
    H5AD_CONVERSION[INPUT_CONVERSION]
    PERSAMPLE_TX[PS_TX_PROCESSING]
    PERSAMPLE_ADT[PS_ADT_PROCESSING]
    PERSAMPLE_RNA_VELO[PS_RNA_VELO_PROCESSING]
    PERSAMPLE_ATAC[PS_ATAC_PROCESSING]
    MERGE((MERGE))
    CONCAT((CONCAT))
    INTEGRATION[INTEGRATION]
    INTERPRETATION(INTERPRETATION)
    AGGREGATION((AGGREGATION))
    ANNOTATION((AGGREGATION))
    CONVERSION[OUTPUT_CONVERSION]
    VDJ_MAPPING
    QUERYING
    CLUSTERING

    classDef implemented fill:#f90,stroke:#444,stroke-width:4px;

    class VDJ_MAPPING implemented
    class DEMULTIPLEX implemented
    class COUNT implemented
    class H5AD_CONVERSION implemented
    class PERSAMPLE_TX implemented
    class CONCAT_TX implemented
    class INTEGRATION_TX implemented
    class CLUSTERING implemented
    class CONVERSION implemented


    subgraph Ingestion
    SEQUENCER ==> |BCL| DEMULTIPLEX ==> |FASTQ| COUNT ==> |COUNT_TABLE| H5AD_CONVERSION
    DEMULTIPLEX --> |FASTQ| VDJ_MAPPING
    end

    VDJ_MAPPING -.-> |CSV/JSON/AIRR| ANNOTATION


    H5AD_CONVERSION -.-> |H5AD_ATAC| PERSAMPLE_ATAC 
    H5AD_CONVERSION -.-> |H5AD_TX| PERSAMPLE_TX 
    H5AD_CONVERSION -.-> |H5AD_ADT| PERSAMPLE_ADT

    H5AD_CONVERSION -.-> |H5AD_RNA_VELO| PERSAMPLE_RNA_VELO

    subgraph Per sample processing
    PERSAMPLE_TX --> |H5AD| MERGE
    PERSAMPLE_ATAC --> |H5AD| MERGE
    PERSAMPLE_ADT --> |H5AD| MERGE
    PERSAMPLE_RNA_VELO  --> |H5AD| MERGE
    end

    MERGE -->|SS_MUON| CONCAT -->|MUON| INTEGRATION --> |MUON| AGGREGATION

    subgraph Integration
    INTEGRATION
    end

    AGGREGATION -.-> |MUON| CELL_CELL_INTERACTION
    AGGREGATION -.-> |MUON| GRN
    AGGREGATION -.-> |MUON| TI
    AGGREGATION -.-> |MUON| CELL_TYPING
    AGGREGATION -.-> |MUON| CLUSTERING
    AGGREGATION -.-> |MUON| QUERYING

    subgraph Transformation
        CELL_CELL_INTERACTION
        GRN
        TI
        CELL_TYPING
        CLUSTERING
        QUERYING
    end



    CELL_CELL_INTERACTION -.-> |DIFF_MUON| ANNOTATION
    GRN -.-> |DIFF_MUON| ANNOTATION
    TI -.-> |DIFF_MUON| ANNOTATION
    CELL_TYPING -.-> |DIFF_MUON| ANNOTATION
    CLUSTERING -.-> |DIFF_MUON| ANNOTATION
    QUERYING -.-> |DIFF_MUON| ANNOTATION 

    ANNOTATION ==> |MUON| CONVERSION

    ANNOTATION -.-> |MUON| PSEUDOBULK
    ANNOTATION -.-> |MUON| QC
    ANNOTATION -.-> |MUON| COMPOSITIONAL_ANALYSIS

    subgraph Reporting
    PSEUDOBULK
    QC
    COMPOSITIONAL_ANALYSIS
    end

    CONVERSION ==> INTERPRETATION

    INTERPRETATION <==> ANNOTATION

    INTEGRATION ==> |MUON| ANNOTATION



