graph TD
    SEQUENCER(SEQUENCER)
    DEMULTIPLEX[DEMULTIPLEX]
    COUNT[MAP/COUNT]
    H5AD_CONVERSION[CONVERSION]
    PERSAMPLE[PER SAMPLE PROCESSING]
    INTEGRATION[INTEGRATION]
    DOWNSTREAM[DOWNSTREAM PROCESSING]
    INTERPRETATION(INTERPRETATION)
    CONVERSION

    SEQUENCER --> |BCL| DEMULTIPLEX --> |FASTQ| COUNT --> |COUNT_TABLE| H5AD_CONVERSION
    H5AD_CONVERSION --> |H5AD| PERSAMPLE 

    PERSAMPLE --> |H5AD| INTEGRATION --> |MULTI_H5AD| DOWNSTREAM
    DOWNSTREAM --> |ANNOTATED_MULTI_H5AD| CONVERSION --> INTERPRETATION