flowchart LR
    SEQUENCER(SEQUENCER)
    DEMULTIPLEX[DEMULTIPLEX]
    COUNT[MAP/COUNT]
    H5AD_CONVERSION[INPUT_CONVERSION]
    PERSAMPLE_TX[PER SAMPLE TX PROCESSING]
    PERSAMPLE_ADT[PER SAMPLE ADT PROCESSING]
    CONCAT_ADT
    CONCAT_TX
    CONCAT_ATAC
    CONCAT_RNA_VELO
    INTEGRATION_TX[INTEGRATION]
    INTEGRATION_ADT[INTEGRATION]
    INTEGRATION_MULTI_OME[INTEGRATION_MULTI_MOD]
    DOWNSTREAM[DOWNSTREAM PROCESSING]
    INTERPRETATION(INTERPRETATION)
    AGGREGATION((AGGREGATION))
    ANNOTATION((AGGREGATION))
    CONVERSION[OUTPUT_CONVERSION]
    VDJ_MAPPING
    CLUSTERING

    classDef implemented fill:#f90,stroke:#444,stroke-width:4px;

    class VDJ_MAPPING implemented
    class DEMULTIPLEX implemented
    class COUNT implemented
    class H5AD_CONVERSION implemented
    class PERSAMPLE_TX implemented
    class CONCAT_TX implemented
    class INTEGRATION_TX implemented
    class CLUSTERING implemented
    class CONVERSION implemented

    subgraph PREPROCESSING
    SEQUENCER ==> |BCL| DEMULTIPLEX ==> |FASTQ| COUNT ==> |COUNT_TABLE| H5AD_CONVERSION
    end

    subgraph VDJ
    DEMULTIPLEX -.-> |CSV/JSON/AIRR| VDJ_MAPPING --> VDJ_REPORTING
    end

    subgraph ATAC
    H5AD_CONVERSION -.-> |ATAC| PERSAMPLE_ATAC --> |H5AD| CONCAT_ATAC -->|MULTI_H5AD| INTEGRATION_ATAC
    end

    subgraph Tx
    H5AD_CONVERSION --> |H5AD_TX| PERSAMPLE_TX --> |H5AD| CONCAT_TX -->|MULTI_H5AD| INTEGRATION_TX
    end

    subgraph ADT
    H5AD_CONVERSION -.-> |H5AD_ADT| PERSAMPLE_ADT --> |H5AD| CONCAT_ADT -->|MULTI_H5AD| INTEGRATION_ADT
    end

    
    H5AD_CONVERSION --> |H5AD_RNA_VELO| PERSAMPLE_RNA_VELO
    subgraph RNA_velocity
    PERSAMPLE_RNA_VELO --> |H5AD| CONCAT_RNA_VELO --> |MULTI_H5AD| INTEGRATION_RNA_VELO
    end
    
    VDJ_MAPPING -.-> |CSV| AGGREGATION

    INTEGRATION_TX --> CONCAT
    INTEGRATION_ADT --> AGGREGATION
    INTEGRATION_RNA_VELO --> AGGREGATION
    INTEGRATION_ATAC --> AGGREGATION

    INTEGRATION_MULTI_OME --> |MUON| ANNOTATION


    AGGREGATION -->|MUON| INTEGRATION_MULTI_OME

    subgraph Multiome_integration
    INTEGRATION_MULTI_OME
    end

    AGGREGATION -.-> |MUON| DE
    AGGREGATION -.-> |MUON| CELL_CELL_INTERACTION
    AGGREGATION -.-> |MUON| GRN
    AGGREGATION -.-> |MUON| TI
    AGGREGATION -.-> |MUON| CELL_TYPING
    AGGREGATION -.-> |MUON| CLUSTERING

    subgraph DOWNSTREAM
        DE[Pseudobulk]
        CELL_CELL_INTERACTION
        GRN
        TI
        CELL_TYPING
        CLUSTERING
    end



    CELL_CELL_INTERACTION -.-> |CSV| ANNOTATION
    GRN -.-> |CSV| ANNOTATION
    TI -.-> |MUON/CSV| ANNOTATION
    CELL_TYPING -.-> |CSV| ANNOTATION
    CLUSTERING -.-> |CSV| ANNOTATION

    AGGREGATION ==> |MUON| ANNOTATION

    ANNOTATION ==> CONVERSION
    ANNOTATION ==> REPORTING

    CONVERSION ==> INTERPRETATION

