flowchart LR
   H5AD_TX_IN(H5AD_TX)
   FILTERING
   SCRUBLET
   LOGNORM
   HVG_SELECTION
   PCA
   NN
   CLUSTERING
   UMAP

   H5AD_TX_IN --> FILTERING --> SCRUBLET --> LOGNORM -->  HVG_SELECTION
   HVG_SELECTION --> PCA --> NN --> UMAP --> CLUSTERING --> H5AD_TX_OUT


