flowchart LR
    SEQUENCER(SEQUENCER)
    DEMULTIPLEX[DEMULTIPLEX]
    COUNT[MAP/COUNT]
    H5AD_CONVERSION[INPUT_CONVERSION]
    PERSAMPLE_TX[PER SAMPLE TX PROCESSING]
    PERSAMPLE_ADT[PER SAMPLE ADT PROCESSING]
    CONCAT
    INTEGRATION_TX[INTEGRATION]
    INTEGRATION_ADT[INTEGRATION]
    INTEGRATION_MULTI_OME[INTEGRATION]
    DOWNSTREAM[DOWNSTREAM PROCESSING]
    INTERPRETATION(INTERPRETATION)
    AGGREGATION
    CONVERSION[OUTPUT_CONVERSION]
    VDJ_MAPPING
    CLUSTERING

    classDef implemented fill:#f9f,stroke:#333,stroke-width:4px;

    class VDJ_MAPPING implemented
    class DEMULTIPLEX implemented
    class COUNT implemented
    class H5AD_CONVERSION implemented
    class PERSAMPLE_TX implemented
    class INTEGRATION_TX implemented
    class CLUSTERING implemented
    class CONVERSION implemented

    subgraph PREPROCESSING
    SEQUENCER ==> |BCL| DEMULTIPLEX ==> |FASTQ| COUNT ==> |COUNT_TABLE| H5AD_CONVERSION
    end

    subgraph ATAC_per_sample
    H5AD_CONVERSION -.-> |ATAC| PERSAMPLE_ATAC
    end

    subgraph Tx_per_sample
    H5AD_CONVERSION ==> |H5AD_TX| PERSAMPLE_TX
    end

    subgraph ADT_per_sample
    H5AD_CONVERSION -.-> |H5AD_ADT| PERSAMPLE_ADT
    end

    PERSAMPLE_TX ==> CONCAT
    PERSAMPLE_ADT --> CONCAT
    PERSAMPLE_ATAC --> CONCAT


    subgraph VDJ
    DEMULTIPLEX -.-> |VDJ| VDJ_MAPPING
    VDJ_MAPPING --> VDJ_REPORTING
    end
    
    VDJ_REPORTING -.->  CONCAT


    CONCAT -->|MULTI_H5AD| INTEGRATION_TX
    CONCAT -->|MULTI_H5AD| INTEGRATION_ADT
    CONCAT -->|MULTI_H5AD| INTEGRATION_MULTI_OME

    subgraph Tx_integration
    INTEGRATION_TX
    end
    subgraph ADT_integration
    INTEGRATION_ADT
    end
    subgraph Multiome_integration
    INTEGRATION_MULTI_OME
    end

    INTEGRATION_TX --> AGGREGATION
    INTEGRATION_ADT --> AGGREGATION
    INTEGRATION_MULTI_OME --> AGGREGATION

    COUNT --> RNA_VELOCITY
    subgraph RNA_velocity
    RNA_VELOCITY
    end
    
    RNA_VELOCITY --> CONCAT

    CONCAT ==>|MULTI_H5AD| AGGREGATION

    AGGREGATION -.-> |MULTI_H5AD| DE
    AGGREGATION -.-> |MULTI_H5AD| CELL_CELL_INTERACTION
    AGGREGATION -.-> |MULTI_H5AD| GRN
    AGGREGATION -.-> |MULTI_H5AD| TI
    AGGREGATION -.-> |MULTI_H5AD| CELL_TYPING
    AGGREGATION -.-> |MULTI_H5AD| CLUSTERING

    subgraph DOWNSTREAM
        DE[Pseudobulk]
        CELL_CELL_INTERACTION
        GRN
        TI
        CELL_TYPING
        CLUSTERING
    end



    DE[Pseudobulk] -.-> |MULTI_H5AD/CSV| ANNOTATION
    CELL_CELL_INTERACTION -.-> |CSV| ANNOTATION
    GRN -.-> |CSV| ANNOTATION
    TI -.-> |MULTI_H5AD/CSV| ANNOTATION
    CELL_TYPING -.-> |CSV| ANNOTATION
    CLUSTERING -.-> |CSV| ANNOTATION

    AGGREGATION ==> |MULTI_H5AD| ANNOTATION
    ANNOTATION ==> CONVERSION


    CONVERSION ==> INTERPRETATION
