flowchart LR
    SEQUENCER(SEQUENCER)
    DEMULTIPLEX[DEMULTIPLEX]
    COUNT[MAP/COUNT]
    H5AD_CONVERSION[INPUT_CONVERSION]
    PERSAMPLE[PER SAMPLE PROCESSING]
    PERSAMPLE_ADT[PER SAMPLE PROCESSING]
    INTEGRATION_TX[INTEGRATION]
    INTEGRATION_ADT[INTEGRATION]
    INTEGRATION_MULTI_OME[COMBINATION]
    CLUSTERING_TX[CLUSTERING]
    CLUSTERING_ADT[CLUSTERING]
    DOWNSTREAM[DOWNSTREAM PROCESSING]
    INTERPRETATION(INTERPRETATION)
    AGGREGATION
    CONVERSION[OUTPUT_CONVERSION]
    ATAC

    subgraph PREPROCESSING
    SEQUENCER ==> |BCL| DEMULTIPLEX ==> |FASTQ| COUNT ==> |COUNT_TABLE| H5AD_CONVERSION
    end

    subgraph ATAC
    H5AD_CONVERSION -.-> |ATAC| ATAC_P
    end

    subgraph VDJ
    DEMULTIPLEX -.-> |VDJ| VDJ_MAPPING
    VDJ_MAPPING --> VDJ_REPORTING
    end

    subgraph Tx
    H5AD_CONVERSION ==> |H5AD_TX| PERSAMPLE 
    PERSAMPLE --> INTEGRATION_TX 
    INTEGRATION_TX --> CLUSTERING_TX
    end

    subgraph ADT
    H5AD_CONVERSION -.-> |H5AD_ADT| PERSAMPLE_ADT
    PERSAMPLE_ADT --> INTEGRATION_ADT
    INTEGRATION_ADT --> CLUSTERING_ADT
    end

    CLUSTERING_TX ==> INTEGRATION_MULTI_OME
    CLUSTERING_ADT -.-> INTEGRATION_MULTI_OME
    ATAC_P -.->  INTEGRATION_MULTI_OME
    VDJ_REPORTING -.-> INTEGRATION_MULTI_OME


    INTEGRATION_MULTI_OME -.-> |MULTI_H5AD| DE
    INTEGRATION_MULTI_OME -.-> |MULTI_H5AD| CELL_CELL_INTERACTION
    INTEGRATION_MULTI_OME -.-> |MULTI_H5AD| GRN
    INTEGRATION_MULTI_OME -.-> |MULTI_H5AD| TI
    INTEGRATION_MULTI_OME -.-> |MULTI_H5AD| CELL_TYPING
    INTEGRATION_MULTI_OME -.-> |MULTI_H5AD| CLUSTERING

    subgraph DOWNSTREAM
        DE[Pseudobulk]
        CELL_CELL_INTERACTION
        GRN
        TI
        CELL_TYPING
        CLUSTERING
    end


    INTEGRATION_MULTI_OME ==> AGGREGATION

    DE[Pseudobulk] -.-> |MULTI_H5AD/CSV| AGGREGATION
    CELL_CELL_INTERACTION -.-> |CSV| AGGREGATION
    GRN -.-> |CSV| AGGREGATION
    TI -.-> |MULTI_H5AD/CSV| AGGREGATION
    CELL_TYPING -.-> |CSV| AGGREGATION
    CLUSTERING -.-> |CSV| AGGREGATION


    AGGREGATION ==> CONVERSION

    CONVERSION ==> INTERPRETATION
