# Dataset Input
param_list: ""
# ---

# Inputs
id: # please fill in - example: "foo"
input: # please fill in - example: "dataset.h5mu"
layer: "log_normalized"
modality: "rna"
# ---

# Outputs
output: # please fill in - example: "$id.$key.output.h5mu"
# ---

# Neighbour Calculation
uns_neighbors: "scanorama_integration_neighbors"
obsp_neighbor_distances: "scanorama_integration_distances"
obsp_neighbor_connectivities: "scanorama_integration_connectivities"
# ---

# Scanorama Integration Options
obs_batch: "sample_id"
obsm_input: "X_pca"
obsm_output: "X_scanorama"
knn: 20
batch_size: 5000
sigma: 15.0
approx: true
alpha: 0.1
# ---

# Clustering Options
obs_cluster: "scanorama_integration_leiden"
leiden_resolution: "1.0"
# ---

# Umap Options
obsm_umap: "X_leiden_scanorama_umap"
# ---

# Nextflow Input-Output Arguments
publish_dir: # please fill in - example: "$id.$key.output/"
# ---
